### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by pgsnimble** [hraban/opus#56]
Hey!!

I am trying to use this library to encode the video and I can't find a way to make it work, everytime I try to build the app I am always getting the following error:

```
 => ERROR [builder-debug 2/2] RUN --mount=type=cache,target=/root/.cache/go-build     go build -gcflags="all=-N -l" -ldflags "-X main.BuildVersion=dev-debug" -o /tmp/gobuild/bin/jbl                            0.5s
------
 > [builder-debug 2/2] RUN --mount=type=cache,target=/root/.cache/go-build     go build -gcflags="all=-N -l" -ldflags "-X main.BuildVersion=dev-debug" -o /tmp/gobuild/bin/jbl:
#0 0.489 # github.com/hraban/opus
#0 0.489 /go/pkg/mod/github.com/hraban/opus@v0.0.0-20230925203106-0188a62cb302/streams_map.go:32:23: undefined: Stream
#0 0.489 /go/pkg/mod/github.com/hraban/opus@v0.0.0-20230925203106-0188a62cb302/streams_map.go:36:40: undefined: Stream
#0 0.489 /go/pkg/mod/github.com/hraban/opus@v0.0.0-20230925203106-0188a62cb302/streams_map.go:42:30: undefined: Stream
#0 0.489 /go/pkg/mod/github.com/hraban/opus@v0.0.0-20230925203106-0188a62cb302/streams_map.go:53:31: undefined: Stream
#0 0.489 /go/pkg/mod/github.com/hraban/opus@v0.0.0-20230925203106-0188a62cb302/streams_map.go:62:25: undefined: Stream
```

Do you mind to help me?

This is a piece of my docker file

```
ARG UBUNTU_IMAGE_VERSION=24.04
ARG YT_DLP=2024.08.06

FROM golang:1.21.3 AS base

ENV CGO_ENABLED=0
ENV GOPRIVATE=github.com/ppaulogustavo

RUN go install github.com/jstemmer/go-junit-report@latest
RUN go install github.com/go-delve/delve/cmd/dlv@latest

WORKDIR /tmp/gobuild
COPY ./go.mod ./go.sum ./
RUN go mod download -x
COPY . .

FROM base as builder-debug
ARG BUILD_VERSION='dev-debug'

RUN apt-get update && apt-get install -y pkg-config libopus-dev libopusfile-dev moreutils

RUN --mount=type=cache,target=/root/.cache/go-build \
    go build -gcflags="all=-N -l" -ldflags "-X main.BuildVersion=${BUILD_VERSION}" -o /tmp/gobuild/bin/jbl
```

This is triggering the error when the build command is executed

**Comment by hraban** [comment]
Hi, weird, it looks like the `stream.go` file isn't available in that directory. Is the directory mounted from somewhere else, without that file? Try an `ls` and see if it exists before building.

**Comment by ErikGoldman** [comment]
I'm having the same issue on Windows. @pgsnimble were you able to solve it?

**Comment by SujithThirumalaisamy** [comment]
Yeah facing the same issue. but working if i build this in my mac without any args. If i build this specifically for linux. from my macbook this seems to throw this error. Every tried copying the files to the local and it still did't work

**Comment by farizap** [comment]
> Yeah facing the same issue. but working if i build this in my mac without any args. If i build this specifically for linux. from my macbook this seems to throw this error. Every tried copying the files to the local and it still did't work

Hi @SujithThirumalaisamy, maybe you need to set CGO_ENABLED=1 because by default it is disabled for cross compiling. For example

`CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o app ./main.go`

**Comment by tbarbugli** [comment]
same error for me (CGO_ENABLED=0), hit this one after upgrading from 1.23 to 1.24. I will share more as I found out

**Comment by visanalexandru** [comment]
I got this error when trying to use `golang:1.25.3-alpine` as the base image in my Dockerfile:


```
FROM golang:1.25.3-alpine AS builder

WORKDIR /build
ADD . /build

RUN apk --no-cache add make git pkgconf opus-dev opusfile-dev

RUN go build  ./cmd/app
```

Error:

```
 => => # /go/pkg/mod/gopkg.in/hraban/opus.v2@v2.0.0-20230925203106-0188a62cb302/streams_map.go:32:23: undefined: Stream
 => => # /go/pkg/mod/gopkg.in/hraban/opus.v2@v2.0.0-20230925203106-0188a62cb302/streams_map.go:36:40: undefined: Stream
 => => # /go/pkg/mod/gopkg.in/hraban/opus.v2@v2.0.0-20230925203106-0188a62cb302/streams_map.go:42:30: undefined: Stream
 => => # /go/pkg/mod/gopkg.in/hraban/opus.v2@v2.0.0-20230925203106-0188a62cb302/streams_map.go:53:31: undefined: Stream
 => => # /go/pkg/mod/gopkg.in/hraban/opus.v2@v2.0.0-20230925203106-0188a62cb302/streams_map.go:62:25: undefined: Stream
```

I fixed it by adding the `gcc` and `musl-dev` packages. So the Dockerfile now looks like this:

```
FROM golang:1.25.3-alpine AS builder

WORKDIR /build
ADD . /build

RUN apk --no-cache add make git gcc musl-dev pkgconf opus-dev opusfile-dev

RUN go build ./cmd/app
```

**Comment by ubivent-seuffert** [comment]
same problem here when trying to build for arm64. building for amd64 is fine

```
GOARCH=arm64 GOOS=linux go build -ldflags="-s -w -X 'project/internal/version.BuildDate=2026-04-02T12:06:26Z'" -o project.arm64 .
# gopkg.in/hraban/opus.v2
../../go/pkg/mod/gopkg.in/hraban/opus.v2@v2.0.0-20230925203106-0188a62cb302/streams_map.go:32:23: undefined: Stream
../../go/pkg/mod/gopkg.in/hraban/opus.v2@v2.0.0-20230925203106-0188a62cb302/streams_map.go:36:40: undefined: Stream
../../go/pkg/mod/gopkg.in/hraban/opus.v2@v2.0.0-20230925203106-0188a62cb302/streams_map.go:42:30: undefined: Stream
../../go/pkg/mod/gopkg.in/hraban/opus.v2@v2.0.0-20230925203106-0188a62cb302/streams_map.go:53:31: undefined: Stream
../../go/pkg/mod/gopkg.in/hraban/opus.v2@v2.0.0-20230925203106-0188a62cb302/streams_map.go:62:25: undefined: Stream
make: *** [Makefile:52: build-arm64] Error 1
```

**Comment by hraban** [comment]
@visanalexandru I was able to repro with your dockerfile. I fixed it, and added it as a test in CI. See the new Dockerfile.alpine for how to build this on alpine.

Package `build-base` made a big difference. Once that was installed, no further config was necessary: CGo was automatically enabled, it found all necessary libs, the `undefined: Stream` problem went away, etc.

I think some other commenters may have had a different issue, but it looks related to cross-compiling, which is explicitly not supported by this wrapper. I'm open to learning how to do it but afaik it's "hard" in CGo.
